### ISSUE TITLE
Many unhandled exceptions after running main.py

### ISSUE THREAD

**Issue by Yoshi24517** [ty-porter/mlb-led-scoreboard-emulated#1]
I plugged in Athletics as my team, and AL West as the division, add my OMW API key and changed the city for weather, and left everything else the same in the config JSON file. Not sure if I did something wrong or not.

The entire thing errors out with this:

```
C:\Users\Yoshi24517\mlb-led-scoreboard-emulated>main.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO (20:55:38): MLB LED Scoreboard Emulated - v1.0.0 (32x32)
C:\Users\Yoshi24517\AppData\Local\Programs\Python\Python37\lib\site-packages\bdfparser\bdfparser.py:347
bdfparser warning: The glyph count next to 'CHARS' keyword is 203, which does not match the actual glyph count 204
ERROR (08:55:38): Value Error while refreshing live game status of Athletics. 5 retries remaining.
Traceback (most recent call last):
  File "C:\Users\Yoshi24517\AppData\Local\Programs\Python\Python37\lib\site-packages\mlbgame\data.py", line 70, in get_raw_box_score
    'rawboxscore.xml'))
  File "C:\Users\Yoshi24517\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Yoshi24517\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Yoshi24517\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\Yoshi24517\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Yoshi24517\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\Yoshi24517\AppData\Local\Programs\Python\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yoshi24517\mlb-led-scoreboard-emulated\data\data.py", line 233, in __game_index_for
    team_index = next((i for i in team_idxs if Status.is_live(mlbgame.overview(self.games[i].game_id))), team_idxs[0])
  File "C:\Users\Yoshi24517\mlb-led-scoreboard-emulated\data\data.py", line 233, in <genexpr>
    team_index = next((i for i in team_idxs if Status.is_live(mlbgame.overview(self.games[i].game_id))), team_idxs[0])
  File "C:\Users\Yoshi24517\AppData\Local\Programs\Python\Python37\lib\site-packages\mlbgame\__init__.py", line 198, in overview
    return mlbgame.game.Overview(mlbgame.game.overview(game_id))
  File "C:\Users\Yoshi24517\AppData\Local\Programs\Python\Python37\lib\site-packages\mlbgame\game.py", line 325, in overview
    raw_box_score = mlbgame.data.get_raw_box_score(game_id)
  File "C:\Users\Yoshi24517\AppData\Local\Programs\Python\Python37\lib\site-packages\mlbgame\data.py", line 72, in get_raw_box_score
    raise ValueError('Could not find a game with that id.')
ValueError: Could not find a game with that id.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Yoshi24517\mlb-led-scoreboard-emulated\main.py", line 34, in <module>
    data = Data(config)
  File "C:\Users\Yoshi24517\mlb-led-scoreboard-emulated\data\data.py", line 45, in __init__
    self.current_game_index = self.game_index_for_preferred_team()
  File "C:\Users\Yoshi24517\mlb-led-scoreboard-emulated\data\data.py", line 219, in game_index_for_preferred_team
    return self.__game_index_for(self.config.preferred_teams[0])
  File "C:\Users\Yoshi24517\mlb-led-scoreboard-emulated\data\data.py", line 245, in __game_index_for
    debug.error("ValueError: Failed to refresh overview for {}".format(self.current_game().game_id))
  File "C:\Users\Yoshi24517\mlb-led-scoreboard-emulated\data\data.py", line 200, in current_game
    return self.games[self.current_game_index]
AttributeError: 'Data' object has no attribute 'current_game_index'
```

**Comment by atadams** [comment]
This is an issue with the MLBGame package. Uninstall MLBGame and reinstall from the latest GitHub commit.

```
pip uninstall mlbgame
pip install git+https://github.com/panzarino/mlbgame.git@0d54c56f18e01467e95329761797b5093bbe940b
```
